main/urls.py
from django.urls import path

from main.views import start_page_view, TestSuiteListView, TestsListView, QuestionsListView

urlpatterns = [
    path('', start_page_view, name='index'),
    path('test_suites/', TestSuiteListView.as_view(), name='test_suites'),
    path('test_suites/<int:test_suite_id>/', TestsListView.as_view(), name='test_suite'),
    path('test_suites/<int:test_suite_id>/tests/<int:test_id>/', QuestionsListView.as_view(), name='test'),
]

testing_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('_nested_admin/', include('nested_admin.urls')),  # Для работы 'nested_admin'

    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),

]

main/models/answer.py
from django.db import models


class Answer(models.Model):
    text = models.TextField(null=False, verbose_name='Текст ответа')
    is_right = models.BooleanField(null=False, default=False, verbose_name='Это правильный ответ?')
    question = models.ForeignKey('Question', on_delete=models.CASCADE, null=False)

    class Meta:
        app_label = 'main'
        db_table = 'answers'
        verbose_name = 'ответ'
        verbose_name_plural = 'ответы'

    def __str__(self):
        return self.text if len(self.text) < 35 else f"{self.text[:32]}..."

main/models/question.py
from django.db import models


class Question(models.Model):
    text = models.TextField(null=False, verbose_name='Текст вопроса')
    test = models.ForeignKey('Test', verbose_name='Тест', on_delete=models.CASCADE)

    class Meta:
        app_label = 'main'
        db_table = 'questions'
        verbose_name = 'вопрос'
        verbose_name_plural = 'вопросы'

    def __str__(self):
        return self.text if len(self.text) < 55 else f"{self.text[:52]}..."

main/models/test.py
from django.db import models

from main.models.test_suite import provide_default_test_suite


class Test(models.Model):
    title = models.CharField(max_length=255, null=False, verbose_name='Тема теста')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлён')
    test_suite = models.ForeignKey('TestSuite', verbose_name='Набор тестов',
                                   default=provide_default_test_suite, on_delete=models.SET_DEFAULT)

    def __str__(self):
        return self.title

    class Meta:
        app_label = 'main'
        db_table = 'tests'
        verbose_name = 'тест'
        verbose_name_plural = 'тесты'

main/models/test_suite.py
from django.db import models


class TestSuite(models.Model):
    name = models.CharField(max_length=255, null=False, verbose_name='Название')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлён')

    def __str__(self):
        return self.name

    class Meta:
        app_label = 'main'
        db_table = 'test_suites'
        verbose_name = 'набор тестов'
        verbose_name_plural = 'наборы тестов'


def provide_default_test_suite() -> int:
    default_test_suite, _ = TestSuite.objects.get_or_create(name='Стандартный набор тестов')
    return default_test_suite.id

main/models/user_result.py
from django.conf import settings
from django.db import models


class UserResult(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Пользователь', on_delete=models.CASCADE)
    question = models.ForeignKey('Question', verbose_name='Вопрос', on_delete=models.CASCADE)
    answer = models.ForeignKey('Answer', verbose_name='Ответ', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user}\t|\t{self.question.text}\t|\t{self.answer}"

    class Meta:
        app_label = 'main'
        db_table = 'user_results'
        verbose_name = 'результат тестирования'
        verbose_name_plural = 'результаты тестирования'

main/views/start.py
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.shortcuts import render


def start_page_view(request: WSGIRequest) -> HttpResponse:
    return render(request=request,
                  template_name='main/start_page.html')

main/views/test.py
from typing import Any

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.handlers.wsgi import WSGIRequest
from django.db.models import QuerySet
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View

from main.models import Question, Test, UserResult, Answer

User = get_user_model()


class QuestionsListView(LoginRequiredMixin, View):
    login_url = settings.LOGIN_REDIRECT_URL
    model = Question

    def get(self, request: WSGIRequest, *args, **kwargs):
        return self.__render()

    def post(self, request: WSGIRequest, *args, **kwargs):
        self.__register_answer()
        return self.__render()

    def __render(self) -> HttpResponse:
        if self.__is_complete_test():
            return render(request=self.request,
                          template_name='main/completed_test.html',
                          context=self.__generate_completed_context())
        return render(request=self.request,
                      template_name='main/uncompleted_test.html',
                      context=self.__generate_uncompleted_context())

    def __is_complete_test(self) -> bool:
        return len(self.__provide_uncompleted_questions()) == 0

    def __provide_uncompleted_questions(self) -> QuerySet[Question]:
        completed_question_ids = self.__user_results().values_list('question', flat=True)
        return Question.objects.filter(test=self.__get_test()).exclude(id__in=completed_question_ids)

    def __user_results(self) -> QuerySet[UserResult]:
        return UserResult.objects.filter(user=self.request.user).filter(question__test=self.__get_test())

    def __get_test(self) -> Test:
        test_id = self.kwargs['test_id']
        return Test.objects.get(pk=test_id)

    def __generate_completed_context(self) -> dict[str, Any]:
        return {
            'test': self.__get_test(),
            'user_answers': self.__user_answers()
        }

    def __user_answers(self) -> QuerySet[Answer]:
        answer_ids = self.__user_results().values_list('answer', flat=True)
        return Answer.objects.filter(id__in=answer_ids)

    def __generate_uncompleted_context(self) -> dict[str, Any]:
        new_question = self.__provide_uncompleted_questions().first()
        return {
            'test': self.__get_test(),
            'question': new_question,
            'answers': new_question.answer_set.order_by('?')  # Случайно перемешиваем
        }

    def __register_answer(self) -> None:
        question_id = int(self.request.POST.get('question_id'))
        selected_answer_ids = [int(id_) for id_ in self.request.POST.getlist('answer_id')]
        for selected_answer_id in selected_answer_ids:
            answer_ = Answer.objects.get(pk=selected_answer_id)
            question_ = Question.objects.get(pk=question_id)
            UserResult.objects.update_or_create(user=self.request.user, question=question_, answer=answer_)

main/views/test_suite.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from main.models import Test


class TestsListView(LoginRequiredMixin, ListView):
    login_url = settings.LOGIN_REDIRECT_URL
    model = Test
    template_name = 'main/test_suite.html'

    def get_queryset(self):
        test_suite_id_: int = self.kwargs['test_suite_id']
        return Test.objects.filter(test_suite_id=test_suite_id_)

main/views/test_suites.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from main.models import TestSuite


class TestSuiteListView(LoginRequiredMixin, ListView):
    login_url = settings.LOGIN_REDIRECT_URL
    model = TestSuite
    template_name = 'main/test_suites.html'

main/templates/main/completed_test.html
{% extends 'base.html' %}

{% block content %}

    <h1>Ваши результаты:</h1>

    <ul>
        {% for question in test.question_set.all %}
            <div class="list-group">
                <h4>{{ question.text }}</h4>
                <div class="list-group">
                    {% for answer in question.answer_set.all %}
                        {% if answer in user_answers %}
                            {% if answer.is_right %}
                                <div class="list-group-item list-group-item-success"><b>{{ answer.text }} ✅</b></div>
                            {% else %}
                                <div class="list-group-item list-group-item-danger"><b>{{ answer.text }} ❌</b></div>
                            {% endif %}
                        {% else %}
                            {% if answer.is_right %}
                                <div class="list-group-item list-group-item-secondary">{{ answer.text }} ✅</div>
                            {% else %}
                                <div class="list-group-item list-group-item-secondary">{{ answer.text }}</div>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </ul>

    <a class="btn btn-secondary" href="{% url 'test_suite' test_suite_id=test.test_suite.id %}">Назад к тестам</a>

{% endblock %}

main/templates/main/start_page.html
{% extends 'base.html' %}

{% block content %}

    <h1>Добро пожаловать на сайт по тестированию</h1>
    <div class="list-group">
        {% if user.is_authenticated %}
            <a class="btn btn-success" href="{% url 'test_suites' %}">К наборам тестов</a>
        {% endif %}
    </div>

{% endblock %}

main/templates/main/test_suite.html
{% extends 'base.html' %}

{% block content %}

    <h1>Тесты из набора:</h1>

    <div class="list-group">
        {% if test_list %}
            {% for test in test_list %}
                <a class="list-group-item list-group-item-success"
                   href="{% url 'test' test_suite_id=test.test_suite.id test_id=test.id %}">{{ test.title }}</a>
            {% endfor %}
        {% else %}

            <p>К сожалению, тут ещё не появилось ни одного теста...</p>

        {% endif %}

        <a class="btn btn-secondary" href="{% url 'test_suites' %}">Назад к тестовым наборам</a>
    </div>

{% endblock %}

main/templates/main/test_suites.html
{% extends 'base.html' %}

{% block content %}
    <h1>Наборы тестов:</h1>

    <div class="list-group">
        {% if testsuite_list %}

            {% for test_suite in testsuite_list %}
                <a class="list-group-item list-group-item-success"
                   href="{% url 'test_suite' test_suite_id=test_suite.id %}">{{ test_suite.name }}</a>
            {% endfor %}

        {% else %}

            <p>К сожалению, тут ещё не появилось ни одного тестового набора...</p>

        {% endif %}

        <a class="btn btn-secondary" href="{% url 'index' %}">На главную</a>

    </div>
{% endblock %}

main/templates/main/uncompleted_test.html
{% extends 'base.html' %}

{% block content %}

    <form action="{% url 'test' test_suite_id=test.test_suite.id test_id=test.id %}" method="post">
        {% csrf_token %}

        <h3>
            {{ question.text }}
            <label><input name="question_id" type="hidden" value="{{ question.id }}"></label>
        </h3>


        {% for answer in answers %}
            {#                    <label>#}
            <div class="form-check">
                <input name="answer_id" value="{{ answer.id }}" class="form-check-input" type="checkbox"
                       id="checkbox-{{ answer.id }}">
                <label class="form-check-label" for="checkbox-{{ answer.id }}">{{ answer.text }}</label>

                {#  <input type="checkbox"  name="answer_id" class="btn-check" id="btn-check-outlined" autocomplete="off" value="{{ answer.id }}">#}
                {#  <label class="btn btn-outline-primary" for="btn-check-outlined">{{ answer.text }}</label><br>#}
                {#                        <input class="checkbox" name="answer_id" type="checkbox" value="{{ answer.id }}"/>#}
                {#                    </label>#}
                {#                    {{ answer.text }}#}
            </div>
        {% endfor %}
        <div class="list-group">
            <input class="btn btn-success" type="submit" value="Далее"/>
            <a class="btn btn-secondary" href="{% url 'test_suite' test_suite_id=test.test_suite.id %}">Назад</a>
        </div>
    </form>

{% endblock %}